// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/appengine/logging/v1/request_log.proto

package com.google.appengine.logging.v1;

/**
 *
 *
 * <pre>
 * Specifies a location in a source code file.
 * </pre>
 *
 * Protobuf type {@code google.appengine.logging.v1.SourceLocation}
 */
@SuppressWarnings("ReferenceEquality")
public final class SourceLocation extends com.google.protobuf.GeneratedMessageV3
    implements
    // @@protoc_insertion_point(message_implements:google.appengine.logging.v1.SourceLocation)
    SourceLocationOrBuilder {
  private static final long serialVersionUID = 0L;
  // Use SourceLocation.newBuilder() to construct.
  private SourceLocation(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }

  private SourceLocation() {
    file_ = "";
    functionName_ = "";
  }

  @Override
  @SuppressWarnings({"unused"})
  protected Object newInstance(UnusedPrivateParameter unused) {
    return new SourceLocation();
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet getUnknownFields() {
    return this.unknownFields;
  }

  private SourceLocation(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10:
            {
              String s = input.readStringRequireUtf8();

              file_ = s;
              break;
            }
          case 16:
            {
              line_ = input.readInt64();
              break;
            }
          case 26:
            {
              String s = input.readStringRequireUtf8();

              functionName_ = s;
              break;
            }
          default:
            {
              if (!parseUnknownField(input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }

  public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
    return RequestLogProto.internal_static_google_appengine_logging_v1_SourceLocation_descriptor;
  }

  @Override
  protected FieldAccessorTable internalGetFieldAccessorTable() {
    return RequestLogProto
        .internal_static_google_appengine_logging_v1_SourceLocation_fieldAccessorTable
        .ensureFieldAccessorsInitialized(SourceLocation.class, Builder.class);
  }

  public static final int FILE_FIELD_NUMBER = 1;
  private volatile Object file_;
  /**
   *
   *
   * <pre>
   * Source file name. Depending on the runtime environment, this might be a
   * simple name or a fully-qualified name.
   * </pre>
   *
   * <code>string file = 1;</code>
   *
   * @return The file.
   */
  @Override
  public String getFile() {
    Object ref = file_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      file_ = s;
      return s;
    }
  }
  /**
   *
   *
   * <pre>
   * Source file name. Depending on the runtime environment, this might be a
   * simple name or a fully-qualified name.
   * </pre>
   *
   * <code>string file = 1;</code>
   *
   * @return The bytes for file.
   */
  @Override
  public com.google.protobuf.ByteString getFileBytes() {
    Object ref = file_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((String) ref);
      file_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int LINE_FIELD_NUMBER = 2;
  private long line_;
  /**
   *
   *
   * <pre>
   * Line within the source file.
   * </pre>
   *
   * <code>int64 line = 2;</code>
   *
   * @return The line.
   */
  @Override
  public long getLine() {
    return line_;
  }

  public static final int FUNCTION_NAME_FIELD_NUMBER = 3;
  private volatile Object functionName_;
  /**
   *
   *
   * <pre>
   * Human-readable name of the function or method being invoked, with optional
   * context such as the class or package name. This information is used in
   * contexts such as the logs viewer, where a file and line number are less
   * meaningful. The format can vary by language. For example:
   * `qual.if.ied.Class.method` (Java), `dir/package.func` (Go), `function`
   * (Python).
   * </pre>
   *
   * <code>string function_name = 3;</code>
   *
   * @return The functionName.
   */
  @Override
  public String getFunctionName() {
    Object ref = functionName_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      functionName_ = s;
      return s;
    }
  }
  /**
   *
   *
   * <pre>
   * Human-readable name of the function or method being invoked, with optional
   * context such as the class or package name. This information is used in
   * contexts such as the logs viewer, where a file and line number are less
   * meaningful. The format can vary by language. For example:
   * `qual.if.ied.Class.method` (Java), `dir/package.func` (Go), `function`
   * (Python).
   * </pre>
   *
   * <code>string function_name = 3;</code>
   *
   * @return The bytes for functionName.
   */
  @Override
  public com.google.protobuf.ByteString getFunctionNameBytes() {
    Object ref = functionName_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((String) ref);
      functionName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;

  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output) throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(file_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, file_);
    }
    if (line_ != 0L) {
      output.writeInt64(2, line_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(functionName_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, functionName_);
    }
    unknownFields.writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(file_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, file_);
    }
    if (line_ != 0L) {
      size += com.google.protobuf.CodedOutputStream.computeInt64Size(2, line_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(functionName_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, functionName_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
      return true;
    }
    if (!(obj instanceof SourceLocation)) {
      return super.equals(obj);
    }
    SourceLocation other = (SourceLocation) obj;

    if (!getFile().equals(other.getFile())) return false;
    if (getLine() != other.getLine()) return false;
    if (!getFunctionName().equals(other.getFunctionName())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + FILE_FIELD_NUMBER;
    hash = (53 * hash) + getFile().hashCode();
    hash = (37 * hash) + LINE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(getLine());
    hash = (37 * hash) + FUNCTION_NAME_FIELD_NUMBER;
    hash = (53 * hash) + getFunctionName().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static SourceLocation parseFrom(java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static SourceLocation parseFrom(
      java.nio.ByteBuffer data, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static SourceLocation parseFrom(com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static SourceLocation parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static SourceLocation parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static SourceLocation parseFrom(
      byte[] data, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static SourceLocation parseFrom(java.io.InputStream input) throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
  }

  public static SourceLocation parseFrom(
      java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3.parseWithIOException(
        PARSER, input, extensionRegistry);
  }

  public static SourceLocation parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(PARSER, input);
  }

  public static SourceLocation parseDelimitedFrom(
      java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(
        PARSER, input, extensionRegistry);
  }

  public static SourceLocation parseFrom(com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
  }

  public static SourceLocation parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3.parseWithIOException(
        PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() {
    return newBuilder();
  }

  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }

  public static Builder newBuilder(SourceLocation prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }

  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   *
   *
   * <pre>
   * Specifies a location in a source code file.
   * </pre>
   *
   * Protobuf type {@code google.appengine.logging.v1.SourceLocation}
   */
  public static final class Builder extends com.google.protobuf.GeneratedMessageV3.Builder<Builder>
      implements
      // @@protoc_insertion_point(builder_implements:google.appengine.logging.v1.SourceLocation)
      SourceLocationOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
      return RequestLogProto.internal_static_google_appengine_logging_v1_SourceLocation_descriptor;
    }

    @Override
    protected FieldAccessorTable internalGetFieldAccessorTable() {
      return RequestLogProto
          .internal_static_google_appengine_logging_v1_SourceLocation_fieldAccessorTable
          .ensureFieldAccessorsInitialized(SourceLocation.class, Builder.class);
    }

    // Construct using com.google.appengine.logging.v1.SourceLocation.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }

    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders) {}
    }

    @Override
    public Builder clear() {
      super.clear();
      file_ = "";

      line_ = 0L;

      functionName_ = "";

      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
      return RequestLogProto.internal_static_google_appengine_logging_v1_SourceLocation_descriptor;
    }

    @Override
    public SourceLocation getDefaultInstanceForType() {
      return SourceLocation.getDefaultInstance();
    }

    @Override
    public SourceLocation build() {
      SourceLocation result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public SourceLocation buildPartial() {
      SourceLocation result = new SourceLocation(this);
      result.file_ = file_;
      result.line_ = line_;
      result.functionName_ = functionName_;
      onBuilt();
      return result;
    }

    @Override
    public Builder clone() {
      return super.clone();
    }

    @Override
    public Builder setField(com.google.protobuf.Descriptors.FieldDescriptor field, Object value) {
      return super.setField(field, value);
    }

    @Override
    public Builder clearField(com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }

    @Override
    public Builder clearOneof(com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }

    @Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field, int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }

    @Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field, Object value) {
      return super.addRepeatedField(field, value);
    }

    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof SourceLocation) {
        return mergeFrom((SourceLocation) other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(SourceLocation other) {
      if (other == SourceLocation.getDefaultInstance()) return this;
      if (!other.getFile().isEmpty()) {
        file_ = other.file_;
        onChanged();
      }
      if (other.getLine() != 0L) {
        setLine(other.getLine());
      }
      if (!other.getFunctionName().isEmpty()) {
        functionName_ = other.functionName_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      SourceLocation parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (SourceLocation) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private Object file_ = "";
    /**
     *
     *
     * <pre>
     * Source file name. Depending on the runtime environment, this might be a
     * simple name or a fully-qualified name.
     * </pre>
     *
     * <code>string file = 1;</code>
     *
     * @return The file.
     */
    public String getFile() {
      Object ref = file_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        file_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     *
     *
     * <pre>
     * Source file name. Depending on the runtime environment, this might be a
     * simple name or a fully-qualified name.
     * </pre>
     *
     * <code>string file = 1;</code>
     *
     * @return The bytes for file.
     */
    public com.google.protobuf.ByteString getFileBytes() {
      Object ref = file_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        file_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     *
     *
     * <pre>
     * Source file name. Depending on the runtime environment, this might be a
     * simple name or a fully-qualified name.
     * </pre>
     *
     * <code>string file = 1;</code>
     *
     * @param value The file to set.
     * @return This builder for chaining.
     */
    public Builder setFile(String value) {
      if (value == null) {
        throw new NullPointerException();
      }

      file_ = value;
      onChanged();
      return this;
    }
    /**
     *
     *
     * <pre>
     * Source file name. Depending on the runtime environment, this might be a
     * simple name or a fully-qualified name.
     * </pre>
     *
     * <code>string file = 1;</code>
     *
     * @return This builder for chaining.
     */
    public Builder clearFile() {

      file_ = getDefaultInstance().getFile();
      onChanged();
      return this;
    }
    /**
     *
     *
     * <pre>
     * Source file name. Depending on the runtime environment, this might be a
     * simple name or a fully-qualified name.
     * </pre>
     *
     * <code>string file = 1;</code>
     *
     * @param value The bytes for file to set.
     * @return This builder for chaining.
     */
    public Builder setFileBytes(com.google.protobuf.ByteString value) {
      if (value == null) {
        throw new NullPointerException();
      }
      checkByteStringIsUtf8(value);

      file_ = value;
      onChanged();
      return this;
    }

    private long line_;
    /**
     *
     *
     * <pre>
     * Line within the source file.
     * </pre>
     *
     * <code>int64 line = 2;</code>
     *
     * @return The line.
     */
    @Override
    public long getLine() {
      return line_;
    }
    /**
     *
     *
     * <pre>
     * Line within the source file.
     * </pre>
     *
     * <code>int64 line = 2;</code>
     *
     * @param value The line to set.
     * @return This builder for chaining.
     */
    public Builder setLine(long value) {

      line_ = value;
      onChanged();
      return this;
    }
    /**
     *
     *
     * <pre>
     * Line within the source file.
     * </pre>
     *
     * <code>int64 line = 2;</code>
     *
     * @return This builder for chaining.
     */
    public Builder clearLine() {

      line_ = 0L;
      onChanged();
      return this;
    }

    private Object functionName_ = "";
    /**
     *
     *
     * <pre>
     * Human-readable name of the function or method being invoked, with optional
     * context such as the class or package name. This information is used in
     * contexts such as the logs viewer, where a file and line number are less
     * meaningful. The format can vary by language. For example:
     * `qual.if.ied.Class.method` (Java), `dir/package.func` (Go), `function`
     * (Python).
     * </pre>
     *
     * <code>string function_name = 3;</code>
     *
     * @return The functionName.
     */
    public String getFunctionName() {
      Object ref = functionName_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        functionName_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     *
     *
     * <pre>
     * Human-readable name of the function or method being invoked, with optional
     * context such as the class or package name. This information is used in
     * contexts such as the logs viewer, where a file and line number are less
     * meaningful. The format can vary by language. For example:
     * `qual.if.ied.Class.method` (Java), `dir/package.func` (Go), `function`
     * (Python).
     * </pre>
     *
     * <code>string function_name = 3;</code>
     *
     * @return The bytes for functionName.
     */
    public com.google.protobuf.ByteString getFunctionNameBytes() {
      Object ref = functionName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        functionName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     *
     *
     * <pre>
     * Human-readable name of the function or method being invoked, with optional
     * context such as the class or package name. This information is used in
     * contexts such as the logs viewer, where a file and line number are less
     * meaningful. The format can vary by language. For example:
     * `qual.if.ied.Class.method` (Java), `dir/package.func` (Go), `function`
     * (Python).
     * </pre>
     *
     * <code>string function_name = 3;</code>
     *
     * @param value The functionName to set.
     * @return This builder for chaining.
     */
    public Builder setFunctionName(String value) {
      if (value == null) {
        throw new NullPointerException();
      }

      functionName_ = value;
      onChanged();
      return this;
    }
    /**
     *
     *
     * <pre>
     * Human-readable name of the function or method being invoked, with optional
     * context such as the class or package name. This information is used in
     * contexts such as the logs viewer, where a file and line number are less
     * meaningful. The format can vary by language. For example:
     * `qual.if.ied.Class.method` (Java), `dir/package.func` (Go), `function`
     * (Python).
     * </pre>
     *
     * <code>string function_name = 3;</code>
     *
     * @return This builder for chaining.
     */
    public Builder clearFunctionName() {

      functionName_ = getDefaultInstance().getFunctionName();
      onChanged();
      return this;
    }
    /**
     *
     *
     * <pre>
     * Human-readable name of the function or method being invoked, with optional
     * context such as the class or package name. This information is used in
     * contexts such as the logs viewer, where a file and line number are less
     * meaningful. The format can vary by language. For example:
     * `qual.if.ied.Class.method` (Java), `dir/package.func` (Go), `function`
     * (Python).
     * </pre>
     *
     * <code>string function_name = 3;</code>
     *
     * @param value The bytes for functionName to set.
     * @return This builder for chaining.
     */
    public Builder setFunctionNameBytes(com.google.protobuf.ByteString value) {
      if (value == null) {
        throw new NullPointerException();
      }
      checkByteStringIsUtf8(value);

      functionName_ = value;
      onChanged();
      return this;
    }

    @Override
    public final Builder setUnknownFields(final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }

    // @@protoc_insertion_point(builder_scope:google.appengine.logging.v1.SourceLocation)
  }

  // @@protoc_insertion_point(class_scope:google.appengine.logging.v1.SourceLocation)
  private static final SourceLocation DEFAULT_INSTANCE;

  static {
    DEFAULT_INSTANCE = new SourceLocation();
  }

  public static SourceLocation getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<SourceLocation> PARSER =
      new com.google.protobuf.AbstractParser<SourceLocation>() {
        @Override
        public SourceLocation parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new SourceLocation(input, extensionRegistry);
        }
      };

  public static com.google.protobuf.Parser<SourceLocation> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<SourceLocation> getParserForType() {
    return PARSER;
  }

  @Override
  public SourceLocation getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }
}
